# -*- coding: utf-8 -*-
"""topicosjoin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EGDLYfGA1UvRUPTYfR-vb6SbQm8qJlaq
"""

import pandas as pd

world = pd.read_csv(
    's3://proyecto3-dataset-hcastro-mortiza/test/ConfirmadosSeguimiento/part-00000-34f9095c-6cd8-423f-899b-ea7d053ac0aa-c000.csv'
)

dates_sum = world.T

dates_sum["fecha"] = dates_sum.index


dates_sum.reset_index(inplace=True)

dates_sum = dates_sum.drop('index', 1)

dates_sum = dates_sum.rename(columns={0: "InfectMundo"})

dates_sum["acumInfectMundo"] = dates_sum["InfectMundo"].cumsum()

dates_sum["fecha"] = dates_sum["fecha"].apply(lambda x: x[4:-1])

dates_sum["fecha"] = pd.to_datetime(dates_sum["fecha"])

col = pd.read_csv(
    "https://proyecto3-dataset-hcastro-mortiza.s3.amazonaws.com/test/Acumulado/part-00000-d5820137-ba49-4d05-a70a-a52a145c9afb-c000.csv"

)

col = col.drop(0)

col = col.rename(columns = {"Fecha de notificación": "fecha", "count": "infectadosCol", "cumsum" : "acumuladosCol"})

col["fecha"] = pd.to_datetime(col["fecha"])

result = col.merge(dates_sum, on='fecha')

result.to_csv("join_mundo_col.csv", index=False)

